baseURL = "https://example.org/"
locale = "zh-CN"
title = "惊蛰"
theme = "jingzhe_v3"

enableRobotsTXT = true
hasCJKLanguage = true
cleanDestinationDir = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.158.0"

[permalinks]
  posts = "/:slug/"

[markup]
  [markup.highlight]
    guessSyntax = true
    lineNos = false
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  laodaotag = "laodaotags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true

  [[related.indices]]
    name = "laodaotags"
    weight = 100

  [[related.indices]]
    name = "date"
    pattern = "200601"
    weight = 10

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS", "JSON"]
